#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE postgres WITH SUPERUSER LOGIN PASSWORD 'postgres';
  ALTER ROLE ${POSTGRES_USER} WITH SUPERUSER LOGIN PASSWORD '${POSTGRES_PASSWORD}';
EOSQL
